Algoritmo "exercicio51"
// Disciplina   : [Lógica de Programação com java acript]
// Professor   : Jailson
// Descrição   : Contador de 101 até 110
// Autor(a)    : Felipe
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
indice: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para indice de 101 ate 110 faca
escreva (indice)
fimpara
Fimalgoritmo