Algoritmo "exercicio50"
// Disciplina   : [Lógica de Programação com java acript]
// Professor   : Jailson
// Descrição   : Contador de 1 até 10 usando o para
// Autor(a)    : Felipe
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
indice: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para indice de 1 ate 10 faca
escreva (indice)
fimpara
Fimalgoritmo