Algoritmo "exercicio58"
// Disciplina   : [Lógica de Programação com java script]
// Professor   : Jailson
// Descrição   : Escreva de 10 até 1 com um contador
// Autor(a)    : Felipe
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
contador: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 10
enquanto contador <> 0 faca
escreva (contador)
contador <- contador - 1
fimenquanto
Fimalgoritmo