Algoritmo "exercicio6 (3)"
// Disciplina   : [Lógica de Programação com java script]
// Professor   : Jailson
// Descrição   : Calcula a área de um circulo usando o raio
// Autor(a)    : Felipe
// Data atual  : 15/03/2023
Var
raio: real
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Raio: ")
leia (raio)
area <- (raio*raio)*(3.14)
escreva("O área do circulo é :", area)
Fimalgoritmo