Algoritmo "exercicio55"
// Disciplina   : [Lógica de Programação com java script]
// Professor   : Jailson
// Descrição   : Faz a tabuada do 8
// Autor(a)    : Felipe
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
indice: inteiro
multiplicacao: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para indice de 1 ate 10 faca
multiplicacao <- 8 * indice
escreval ("8 X",indice, " =",multiplicacao)
fimpara
Fimalgoritmo