Algoritmo "exercicio57"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Escrever numeros de 1 ate 10 com um contador
// Autor(a)    : Felipe
// Data atual  : 21/03/2023
Var
// Seção de Declarações das variáveis 
contador: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador <- 1
repita
escreva(contador)
contador <- contador + 1
ate contador = 11
Fimalgoritmo